set_property IOSTANDARD LVCMOS33 [get_ports {code[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tubePos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLR_n]
set_property IOSTANDARD LVCMOS33 [get_ports CP]
set_property IOSTANDARD LVCMOS33 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports hour_setting]
set_property IOSTANDARD LVCMOS33 [get_ports isSetting]
set_property IOSTANDARD LVCMOS33 [get_ports isSettingAlarm]
set_property IOSTANDARD LVCMOS33 [get_ports minute_setting]
set_property IOSTANDARD LVCMOS33 [get_ports showMode]
set_property PACKAGE_PIN J17 [get_ports {tubePos[0]}]
set_property PACKAGE_PIN J18 [get_ports {tubePos[1]}]
set_property PACKAGE_PIN T9 [get_ports {tubePos[2]}]
set_property PACKAGE_PIN J14 [get_ports {tubePos[3]}]
set_property PACKAGE_PIN P14 [get_ports {tubePos[4]}]
set_property PACKAGE_PIN T14 [get_ports {tubePos[5]}]
set_property PACKAGE_PIN K2 [get_ports {tubePos[6]}]
set_property PACKAGE_PIN U13 [get_ports {tubePos[7]}]
set_property PACKAGE_PIN N17 [get_ports CLR_n]
set_property PACKAGE_PIN E3 [get_ports CP]
set_property PACKAGE_PIN H15 [get_ports dot]
set_property PACKAGE_PIN P17 [get_ports hour_setting]
set_property PACKAGE_PIN V10 [get_ports isSetting]
set_property PACKAGE_PIN U11 [get_ports isSettingAlarm]
set_property PACKAGE_PIN M17 [get_ports minute_setting]
set_property PACKAGE_PIN U12 [get_ports showMode]
set_property PACKAGE_PIN T10 [get_ports {code[0]}]
set_property PACKAGE_PIN R10 [get_ports {code[1]}]
set_property PACKAGE_PIN K16 [get_ports {code[2]}]
set_property PACKAGE_PIN K13 [get_ports {code[3]}]
set_property PACKAGE_PIN P15 [get_ports {code[4]}]
set_property PACKAGE_PIN T11 [get_ports {code[5]}]
set_property PACKAGE_PIN L18 [get_ports {code[6]}]

create_clock -period 10.000 -name CP -waveform {0.000 5.000} [get_ports CP]
create_clock -period 100.000 -name minute_setting [get_ports minute_setting]
create_clock -period 100.000 -name hour_setting [get_ports hour_setting]


set_property IOSTANDARD LVCMOS33 [get_ports botton]
set_property PACKAGE_PIN M18 [get_ports botton]
set_property PACKAGE_PIN V11 [get_ports led_alarm]
set_property IOSTANDARD LVCMOS33 [get_ports led_alarm]

set_property IOSTANDARD LVCMOS33 [get_ports led_int]
set_property PACKAGE_PIN H17 [get_ports led_int]
